# Generated by Django 5.0.6 on 2024-05-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="carton_sizes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codename", models.CharField(max_length=255)),
                ("length", models.CharField(max_length=4)),
                ("width", models.CharField(max_length=4)),
                ("height", models.CharField(max_length=4)),
            ],
        ),
    ]
