# Generated by Django 5.0.6 on 2024-05-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carton_sizes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carton_sizes",
            name="height",
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="carton_sizes",
            name="length",
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name="carton_sizes",
            name="width",
            field=models.IntegerField(max_length=4),
        ),
    ]
