# Generated by Django 5.0.6 on 2024-05-22 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "carton_sizes",
            "0002_alter_carton_sizes_height_alter_carton_sizes_length_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="carton_sizes",
            name="height",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="carton_sizes",
            name="length",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150000),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="carton_sizes",
            name="width",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150000),
                ]
            ),
        ),
    ]
