# Generated by Django 5.0.6 on 2024-05-22 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "carton_sizes",
            "0003_alter_carton_sizes_height_alter_carton_sizes_length_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carton_sizes",
            name="folding_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carton_sizes",
            name="material",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="carton_sizes",
            name="thickness",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(20),
                ],
            ),
        ),
    ]
